service: spotify-release-tracker

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  stage: ${opt:stage}
  environment:
    SPOTIFY_CLIENT_ID: ${self:custom.config.spotify.clientId}
    SPOTIFY_CLIENT_SECRET: ${self:custom.config.spotify.clientSecret}
    SPOTIFY_REDIRECT_URI: ${self:custom.config.spotify.redirectUri}
    SPOTIFY_SCOPES: ${self:custom.config.spotify.scopes}
    SPOTIFY_STATE: ${self:custom.config.spotify.state}
    USERS_TABLE_NAME: ${ssm:/${self:service}/${self:provider.stage}/dynamo/users/name}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-iam-roles-per-function

package:
  individually: true

custom:
  config: ${file(env/${self:provider.stage}.json)}
  webpack:
    packager: yarn
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  login:
    handler: src/endpoints/login/lambda.handler
    events:
      - http:
          method: get
          path: api/auth/login
  authCallback:
    handler: src/endpoints/authCallback/lambda.handler
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: ${ssm:/${self:service}/${self:provider.stage}/dynamo/users/arn}
    events:
      - http:
          method: get
          path: api/auth/callback
